name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev]
    types:
      - completed

jobs:
  pytest:

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: my_database
          POSTGRES_USER: my_user
          POSTGRES_PASSWORD: my_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MEMORY_LIMIT_MB: 4096
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull myashka/big_data_app:latest

    - name: Run Docker container (without starting FastAPI)
      run: docker run -d --name big_data_container myashka/big_data_app:latest tail -f /dev/null

    - name: Execute tests inside Docker container
      run: docker exec big_data_container poetry run pytest src/unit_tests/

    - name: Execute integration tests inside Docker container
      run: docker exec big_data_container poetry run pytest tests/

    - name: Stop services
      if: always()
      run: docker-compose down