name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev]
    types:
      - completed

jobs:
  pytest:
    env:
      MEMORY_LIMIT_MB: 4096

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull myashka/big_data_app:latest

    - name: Create .env file
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    - name: Start services
      run: docker-compose up -d

    # - name: Run Docker container (without starting FastAPI)
    #   run: docker run -d --name big_data_container myashka/big_data_app:latest tail -f /dev/null

    - name: Execute unit tests inside Docker container
      run: docker exec -T app poetry run pytest src/unit_tests/

    # - name: Execute integration tests inside Docker container
      # run: docker exec big_data_container poetry run pytest tests/

    - name: Stop services
      if: always()
      run: docker-compose down